### ISSUE TITLE
能够添加tun模式

### ISSUE THREAD

**Issue by f4nff** [juicity/juicity#119]
### Proposal

希望把tun模式整合进去,
这样丢到openwrt里面就很安逸了.

[https://github.com/xjasonlyu/tun2socks](https://github.com/xjasonlyu/tun2socks)

### Potential Benefits

iptables 逐渐被淘汰了.

### Reference

https://github.com/apernet/hysteria/tree/hy1

hysteria的1版本整合进去了,
但是hysteria  bug有点多,放弃了.

**Comment by mzz2017** [comment]
@f4nff nftables 也被淘汰了吗

**Comment by f4nff** [comment]
目前来说,openwrt原生界面对tun的支持是最好的.

**Comment by f4nff** [comment]
```
{
  "listen": ":1080",
  "server": "[2a07:1040:2:1::1]:33182",
  "uuid": "8e21e704-9ac8-4fb8-bef1-6c9d7d7e390b",
  "password": "RnJ5BfJ3",
  "sni": "www.1o231v.cn",
  "allow_insecure": true,
  "congestion_control": "bbr",
  "log_level": "off"
}
```


```
D:\quic\juicity>client.exe run -c config.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0xe5156e]

goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).should(0xc0001b8700?, 0x98?)
        /home/gopkg/pkg/mod/github.com/rs/zerolog@v1.30.0/log.go:491 +0xe
github.com/rs/zerolog.(*Logger).newEvent(0x0, 0x4, 0x1010e10)
        /home/gopkg/pkg/mod/github.com/rs/zerolog@v1.30.0/log.go:466 +0x36
github.com/rs/zerolog.(*Logger).Fatal(...)
        /home/gopkg/pkg/mod/github.com/rs/zerolog@v1.30.0/log.go:388
main.glob..func1(0xc0001b8600?, {0xfc4a90?, 0x4?, 0xfc4a94?})
        /root/juicity/cmd/client/run.go:51 +0x12f
github.com/spf13/cobra.(*Command).execute(0x13dc520, {0xc0000353c0, 0x2, 0x2})
        /home/gopkg/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x13dc240)
        /home/gopkg/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /home/gopkg/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.Execute(...)
        /root/juicity/cmd/client/cmd.go:22
main.main()
        /root/juicity/cmd/client/client.go:6 +0x1a
```

**Comment by f4nff** [comment]
不支持服务端ipv6格式?

**Comment by mzz2017** [comment]
@f4nff 不要写 off，写 error

**Comment by f4nff** [comment]
```
D:\quic\juicity>client.exe  run -h
To run juicity-client in the foreground.

Usage:
  juicity-client run [flags]

Flags:
  -c, --config string              specify config file path
      --disable-timestamp          deprecated; use log-disable-timestamp instead
  -h, --help                       help for run
      --log-disable-color          disable colorful log output
      --log-disable-timestamp      disable timestamp
      --log-file string            log file path to write (default "/var/log/juicity-client.log")
      --log-file-compress          enable log compression; default: true (default true)
      --log-file-format string     specify log format; options: [raw|json] (default "raw")
      --log-file-max-age int       specify the maximum number of days to retain old log files based on the timestamp encoded in their filename; unit: day (default 1)
      --log-file-max-backups int   specify the maximum number of old log files to retain (default 1)
      --log-file-max-size int      specify maximum size of the log file before it gets rotated; unit: MB (default 10)
      --log-output string          specify the log outputs; options: [console|file|console,file] (default "console")
```


关闭日志的参数是什么???
  "log_level": "info"

**Comment by f4nff** [comment]
目前测试,体验还说得过去,
期待添加tun模式,这样windows下直接可以全局代理.

**Comment by f4nff** [comment]
我先挂路由器上试试看了.有问题再反馈.

**Comment by MarksonHon** [comment]
大佬有兴趣给 [v2rayA](https://github.com/v2rayA/v2rayA) 加上 Tun 模式么

**Comment by f4nff** [comment]
```
	return &Server{
		logger:                 opts.Logger,
		relay:                  relay.NewRelay(opts.Logger),
		dialer:                 &netproxy.ContextDialerConverter{Dialer: d},
		tlsConfig:              &tls.Config{NextProtos: []string{"h3"}, MinVersion: tls.VersionTLS13, Certificates: []tls.Certificate{cert}},
		maxOpenIncomingStreams: 100,
		congestionControl:      opts.CongestionControl,
		cwnd:                   10,
		users:                  users,
		fwmark:                 opts.Fwmark,
		disableOutboundUdp443:  opts.DisableOutboundUdp443,
		inFlightUnderlayKey:    NewInFlightUnderlayKey(inFlightUnderlayTtl),
		udpEndpointPool:        NewUdpEndpointPool(),
	}, nil
}
```


经过并发10000测试,
发现建立了很多传输隧道,
并且在连接数消失之后,也不会主动释放关闭这些已经打开的隧道.

**Comment by f4nff** [comment]
![image](https://github.com/juicity/juicity/assets/19538878/d5760f0b-18e9-4034-bfa0-9d3b1ffdb6f3)

**Comment by mzz2017** [comment]
@f4nff 那肯定不是马上就关闭的

**Comment by f4nff** [comment]
@mzz2017 需要多久? 有时间设置吗?

**Comment by f4nff** [comment]
应该动态设置这个,比如现在连接数超过一个值(100),就再开一个隧道,
如果现在连接数就50了,应该把会话转移到其中一个,其他的主动关闭.

**Comment by f4nff** [comment]
现在的情况是,如果开了很多隧道,明显感觉响应变慢了,变卡顿了.

**Comment by yqlbu** [comment]
@f4nff https://t.me/c/1673505809/20890

**Comment by f4nff** [comment]
无法访问呀,发个群,加一下.

**Comment by yqlbu** [comment]
> @mzz2017 需要多久? 有时间设置吗?

https://github.com/juicity/juicity/blob/main/common/consts/relay.go#L8-L12

```go
// default value for relay (internal/relay)
const (
	EthernetMtu       = 1500
	DefaultNatTimeout = 3 * time.Minute
	DnsQueryTimeout   = 17 * time.Second // RFC 5452
)
```

**Comment by yqlbu** [comment]
> 无法访问呀,发个群,加一下.

https://t.me/+VePoazAb0s1lYmM1

**Comment by MarksonHon** [comment]
@f4nff 他想引用的其实就是这条

**Comment by f4nff** [comment]
```
// default value for relay (internal/relay)
const (
	EthernetMtu       = 1500
	DefaultNatTimeout = 3 * time.Minute
	DnsQueryTimeout   = 17 * time.Second // RFC 5452
)
```

我可以确定,3分钟绝对没有释放.

**Comment by f4nff** [comment]
你可以并发进行测试.

**Comment by f4nff** [comment]
如果我并发10000测试,然后现在开了100个隧道,
然后关闭并发,现在还有其他100个连接,这100个连接会不会把会话转移到一个隧道,
关闭其他的99个.

**Comment by f4nff** [comment]
juicity 有问题,
同样的节点,我用tuic刷网页,不卡的,
但是用juicity一直在转圈.

**Comment by f4nff** [comment]
juicity 处理明显是有问题的,同样的线路,
tuic打开是一点也不卡,
juicity 已经打开的ssh操作也不卡,但是新打开网页,一直卡在那里,
很明显juicity处理是有问题的.
