### ISSUE TITLE
[Bug Report] ARM鸡/Alpine Linux，启动不久后出现Panic退出

### ISSUE THREAD

**Issue by juicyroastgoose** [juicity/juicity#137]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

ARM64鸡/Alpine Linux，可以正常启动，绑定端口，也可以连接，但不久后出现Panic退出。
panic: inconsistent packet size (26 vs 1342)

goroutine 42 [running]:
github.com/mzz2017/quic-go.(*sconn).Write(0x40002ac780, {0x4000246000, 0x1a, 0x5000}, 0x53e)
        github.com/mzz2017/quic-go@v0.0.0-20230902042923-a727c1c479d4/send_conn.go:66 +0x260
github.com/mzz2017/quic-go.(*sendQueue).Run(0x40002538f0)
        github.com/mzz2017/quic-go@v0.0.0-20230902042923-a727c1c479d4/send_queue.go:84 +0x124
github.com/mzz2017/quic-go.(*connection).run.func2()
        github.com/mzz2017/quic-go@v0.0.0-20230902042923-a727c1c479d4/connection.go:519 +0x30
created by github.com/mzz2017/quic-go.(*connection).run in goroutine 39
        github.com/mzz2017/quic-go@v0.0.0-20230902042923-a727c1c479d4/connection.go:518 +0x144

### Expected Behavior

正常运行不退出

### Steps to Reproduce

正常启动（命令行手动启动或者自动启动），客户端连接后不久，服务器juicity-server进程panic退出

### Environment

- **Juicity version (use `juicity --version`)**: 0.3.0
- **OS (e.g `cat /etc/os-release`)**: Alpine 3.18.4
- **Kernel (e.g. `uname -a`)**: 5.15.0
- **Others**: 无

系统版本Alpine Linux 3.18.4，Kernel 5.15.0，Juicity 0.3.0 (https://github.com/juicity/juicity/releases/download/v0.3.0/juicity-linux-arm64.zip)

### Anything else?

无

**Comment by juicyroastgoose** [comment]
同一台鸡，换成debian 12以后问题就消失了，所以猜测可能是arm版musl的问题？

**Comment by molezz** [comment]
ubuntu 有类似问题，
```
panic: inconsistent packet size (4946 vs 1252)

goroutine 17 [running]:
github.com/mzz2017/quic-go.(*sconn).Write(0xc0000bca80, {0xc00025c000, 0x1352, 0x5000}, 0x4e4)
        github.com/mzz2017/quic-go@v0.0.0-20230902042923-a727c1c479d4/send_conn.go:66 +0x2b4
github.com/mzz2017/quic-go.(*sendQueue).Run(0xc0001dad50)
        github.com/mzz2017/quic-go@v0.0.0-20230902042923-a727c1c479d4/send_queue.go:84 +0x166
github.com/mzz2017/quic-go.(*connection).run.func2()
        github.com/mzz2017/quic-go@v0.0.0-20230902042923-a727c1c479d4/connection.go:519 +0x25
created by github.com/mzz2017/quic-go.(*connection).run in goroutine 14
        github.com/mzz2017/quic-go@v0.0.0-20230902042923-a727c1c479d4/connection.go:518 +0x1ad
```
环境
```
Juicity version (use juicity --version): 0.3.0
OS (e.g cat /etc/os-release): Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-91-generic x86_64)
Kernel (e.g. uname -a): GNU/Linux 5.15.0-91-generic x86_64)
Others: ipv6 only机器
```

**Comment by TnZzZHlp** [comment]
```
Dec 27 01:42:47 172-16-1-176 juicity-server[46379]: panic: inconsistent packet size (25 vs 1402)
Dec 27 01:42:47 172-16-1-176 juicity-server[46379]: goroutine 17 [running]:
Dec 27 01:42:47 172-16-1-176 juicity-server[46379]: github.com/mzz2017/quic-go.(*sconn).Write(0xc0000c4c00, {0xc000264000, 0x19, 0x5000}, 0x57a)
Dec 27 01:42:47 172-16-1-176 juicity-server[46379]:         github.com/mzz2017/quic-go@v0.0.0-20230902042923-a727c1c479d4/send_conn.go:66 +0x2b4
Dec 27 01:42:47 172-16-1-176 juicity-server[46379]: github.com/mzz2017/quic-go.(*sendQueue).Run(0xc0001eb7a0)
Dec 27 01:42:47 172-16-1-176 juicity-server[46379]:         github.com/mzz2017/quic-go@v0.0.0-20230902042923-a727c1c479d4/send_queue.go:84 +0x166
Dec 27 01:42:47 172-16-1-176 juicity-server[46379]: github.com/mzz2017/quic-go.(*connection).run.func2()
Dec 27 01:42:47 172-16-1-176 juicity-server[46379]:         github.com/mzz2017/quic-go@v0.0.0-20230902042923-a727c1c479d4/connection.go:519 +0x25
Dec 27 01:42:47 172-16-1-176 juicity-server[46379]: created by github.com/mzz2017/quic-go.(*connection).run in goroutine 14
Dec 27 01:42:47 172-16-1-176 juicity-server[46379]:         github.com/mzz2017/quic-go@v0.0.0-20230902042923-a727c1c479d4/connection.go:518 +0x1ad
Dec 27 01:42:47 172-16-1-176 systemd[1]: juicity-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```
同样遇到问题
环境: LXC Debian12

**Comment by TnZzZHlp** [comment]
> ubuntu 有类似问题，
> 
> ```
> panic: inconsistent packet size (4946 vs 1252)
> 
> goroutine 17 [running]:
> github.com/mzz2017/quic-go.(*sconn).Write(0xc0000bca80, {0xc00025c000, 0x1352, 0x5000}, 0x4e4)
>         github.com/mzz2017/quic-go@v0.0.0-20230902042923-a727c1c479d4/send_conn.go:66 +0x2b4
> github.com/mzz2017/quic-go.(*sendQueue).Run(0xc0001dad50)
>         github.com/mzz2017/quic-go@v0.0.0-20230902042923-a727c1c479d4/send_queue.go:84 +0x166
> github.com/mzz2017/quic-go.(*connection).run.func2()
>         github.com/mzz2017/quic-go@v0.0.0-20230902042923-a727c1c479d4/connection.go:519 +0x25
> created by github.com/mzz2017/quic-go.(*connection).run in goroutine 14
>         github.com/mzz2017/quic-go@v0.0.0-20230902042923-a727c1c479d4/connection.go:518 +0x1ad
> ```
> 
> 环境
> 
> ```
> Juicity version (use juicity --version): 0.3.0
> OS (e.g cat /etc/os-release): Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-91-generic x86_64)
> Kernel (e.g. uname -a): GNU/Linux 5.15.0-91-generic x86_64)
> Others: ipv6 only机器
> ```

mzz大佬修好了要不测一下?
https://github.com/juicity/juicity/actions/runs/7362684976
